---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base-cluster
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: teuto-net
        namespace: flux-system
      version: 6.x.x
  interval: 1m0s
  values:
    flux:
      gitRepositories:
        - name: base-cluster  
          url: ssh://git@github.com/stuelp/Kubernetes-Config-Sarah
          branch: main
          path: ./clusters/{{.Values.global.clusterName}}
    global: {}
          
          

